---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc8
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
 